Repository openHPI/poseidon, pull requests merged in 2021-12, with the labels that each got.

#71 Unwrap Nomad Error for Allocation Exec
  internal/nomad/api_querier.go
  internal/nomad/api_querier_test.go
Labels: bug

#74 Update Dependencies
  .github/workflows/ci.yml
  go.mod
  go.sum
Labels: dependencies

#80 Update default image in template-environment-job.hcl
  internal/environment/template-environment-job.hcl
Labels: enhancement

#79 Improve documentation for Network support in Nomad
  docs/configuration.md
  docs/resources/client.example.hcl
Labels: documentation

#83 Add a warning when allocations fail
  internal/nomad/nomad.go
Labels: enhancement
